### ISSUE TITLE
Empty space at end of folder names

### ISSUE THREAD

**Issue by nnoc** [C0D3D3V/Moodle-Downloader-2#133] opened 2022-01-26 18:09 UTC
## Describe the bug
Basically, one of the folders in a resource has a space at the end of its name, like this: "example ".
While all the other folders do not have it and everything is fine, this one gives an error on download.

```
DEBUG  {main}  Start downloading changed files...
DEBUG  {download_service}  Queue contains 1 URLTargets
DEBUG  {downloader}  T0 - Downloader thread was started
DEBUG  {url_target}  T0 - Starting downloading of: URLTarget (File (module_id: 416232, section_name: "example", section_id: "40294", module_name: "example", content_filepath: /Written exam /, content_filename: "Exam.pdf", content_fileurl: "https://example/webservice/pluginfile.php/1151885/mod_folder/content/5/Written%20Exam%20/Exam.pdf?forcedownload=1", content_filesize: 103999, content_timemodified: 1643135902, module_modname: folder, content_type: file, content_isexternalfile: False, saved_to: "", time_stamp: 0, modified: False, moved: False, deleted: False, notified: False, hash: None, file_id: None, old_file_id: None), Course (id: 4455, fullname: "example course name", overwrite_name_with: "None", create_directory_structure: True, files: 1), False, Error: None)
DEBUG  {url_target}  T0 - Seting up target file: "C:\example\Written exam \Exam.pdf"
DEBUG  {downloader}  T1 - Downloader thread was started
DEBUG  {downloader}  T1 - Downloader thread is finished
ERROR  {url_target}  T0 - Failed seting up target file: "C:\example\Written exam \Exam.pdf"
ERROR  {url_target}  T0 - Error while trying to download file: URLTarget (File (module_id: 416232, section_name: "example", section_id: "40294", module_name: "example", content_filepath: /Written exam /, content_filename: "Exam.pdf", content_fileurl: "https://example/webservice/pluginfile.php/1151885/mod_folder/content/5/Written%20Exam%20/Exam.pdf?forcedownload=1", content_filesize: 103999, content_timemodified: 1643135902, module_modname: folder, content_type: file, content_isexternalfile: False, saved_to: "C:\example\Written exam \Exam.pdf", time_stamp: 0, modified: False, moved: False, deleted: False, notified: False, hash: None, file_id: None, old_file_id: None), Course (id: 4455, fullname: "example course name", overwrite_name_with: "None", create_directory_structure: True, files: 1), False, Error: [Errno 2] No such file or directory: 'C:\\example\\Written exam \\Exam.pdf')
DEBUG  {downloader}  T2 - Downloader thread was started
DEBUG  {downloader}  T2 - Downloader thread is finished
DEBUG  {downloader}  T3 - Downloader thread was started
DEBUG  {downloader}  T3 - Downloader thread is finished
ERROR  {url_target}  T0 - Traceback:
Traceback (most recent call last):
  File "c:\program files\python39\lib\site-packages\moodle_dl\download_service\url_target.py", line 846, in download
    self.set_path()
  File "c:\program files\python39\lib\site-packages\moodle_dl\download_service\url_target.py", line 698, in set_path
    self.file.saved_to = self._rename_if_exists(self.file.saved_to)
  File "c:\program files\python39\lib\site-packages\moodle_dl\download_service\url_target.py", line 168, in _rename_if_exists
    raise e
  File "c:\program files\python39\lib\site-packages\moodle_dl\download_service\url_target.py", line 164, in _rename_if_exists
    open(new_path, 'a').close()
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\example\\Written exam \\Exam.pdf'
DEBUG  {downloader}  T4 - Downloader thread was started
DEBUG  {downloader}  T4 - Downloader thread is finished
DEBUG  {downloader}  T0 - URLTarget reports failure!
DEBUG  {downloader}  T0 - Downloader thread is finished
INFO  {main}  No changes found for the configured Moodle-Account.
```
## Steps to reproduce the issue
Start the script as usual while having a resource with a space at the end of a folder name. Not sure if the same happens with files.

## Technical details
OS: Windows 10 19043

## Expected behaviour
Normally it would download the file to the folder without the space at the end.
Windows removes any spaces at the end of names.

## Possible Fix
Detect empty spaces at the end of folder/file names and remove them? The person who added this folder on the moodle resource probably does not know there was a space there.

**Comment by C0D3D3V** [comment] 2022-01-26 19:06
This should be impossibe, since we strip every space from beginning and end of all parts of a path. Only the storage path is used as it is.

**Comment by nnoc** [comment] 2022-01-26 19:09
Not sure how I can help you reproduce it, but here's how it looks on the normal moodle website:
![image](https://user-images.githubusercontent.com/4395401/151230111-21a86423-3a53-486a-a70d-f3635ee8077c.png)

**Comment by C0D3D3V** [comment] 2022-01-26 19:12
tell me what version do you use: `moodle-dl --version`

**Comment by nnoc** [comment] 2022-01-26 19:13
> tell me what version do you use: `moodle-dl --version`

moodle-dl 2.2.1.4

**Comment by C0D3D3V** [comment] 2022-01-26 19:16
First of all this is a windows only bug. Because only windows cares about spaces in paths. So I have to boot up my windows enviromant, then I will try to reproduce this... This will take a moment.

**Comment by C0D3D3V** [comment] 2022-01-26 19:56
As you can see from the pictures, our sanitizer reliably removes spaces from all parts of a path. I created a course with one section and several files, each of which contained several spaces at the end. Everything was downloaded reliably. Since you have manipulated/falsified your error log, I cannot help you. Please provide the real log.

![1](https://user-images.githubusercontent.com/14315968/151236697-68035842-f9d6-4fc7-b99b-803822563dbb.png)

![2](https://user-images.githubusercontent.com/14315968/151236704-6c627dee-2bb1-454a-af01-f6ae9c637725.png)

https://github.com/C0D3D3V/Moodle-Downloader-2/blob/d5e60fc4e06758231a1e1878df457ee50d52dd05/moodle_dl/download_service/path_tools.py#L12-L40

**Comment by nnoc** [comment] 2022-01-26 20:01
I've uploaded a copy of the log with --verbose without any changes to it here: https://pastebin.com/pHf5d8Gn

**Comment by C0D3D3V** [comment] 2022-01-26 20:05
See that's helpful after all :) Very good thanks. It is the `content_filepath`, which is actually also taken over as it is, I must change that now.

**Comment by nnoc** [comment] 2022-01-26 20:07
Thanks for taking a look into this, this is very helpful for me especially with email notifications as I do not have to worry about checking the courses every day manually for changes!

**Comment by C0D3D3V** [comment] 2022-01-26 20:15
Very gladly, you are welcome. I'll try to fix this now, if it does not work it will probably be fixed on the weekend.

**Closed** 2022-01-26 20:43 UTC
Labels: bug

**Comment by C0D3D3V** [comment] 2022-01-26 20:49
Is fixed in the new version. Thank you for your support :+1:

**Comment by C0D3D3V** [comment] 2022-01-26 20:55
xD in v2.2.1.6 because I accidentally misspelled sanitize_path in one of the cases....
