### ISSUE TITLE
Not recognise course unsubscription

### ISSUE THREAD

**Issue by marcoscale98** [C0D3D3V/Moodle-Downloader-2#84] opened 2021-03-11 22:42 UTC
## Avoid duplicates
* [X] Bug is not already reported in another issue

## Describe the bug

 I unsubscribed from 2 courses and when I updated the folders some files appeared as removed (on the console). The files were not actually removed from the course. I think it is the fact that an error occurs because it cannot recover them (since I have unsubscribed).

## Steps to reproduce the issue

- Download a course
- Unsubscribe from a course
- Try to download again the course

## Technical details
 - OS: Windows 10
 - Version: 2.1.2.5

## Expected behavior

Do not report anything on the console and set the course as unsubscribed. Or should I do it manually? but how?

**Comment by C0D3D3V** [comment] 2021-03-12 06:22
A log file is here very importend. 

But in principle it doesn't matter if a file is marked as removed. It's just stupid because it will be downloaded again when you activate the course again. 

It is actually very unusual that a file of an unsubscribed course is marked as deleted. This should actually be filtered very reliably. Are you sure that you have unsubscripted the course.

**Comment by marcoscale98** [comment] 2021-03-12 08:04
> A log file is here very importend.
> 
> But in principle it doesn't matter if a file is marked as removed. It's just stupid because it will be downloaded again when you activate the course again.
> 
> It is actually very unusual that a file of an unsubscribed course is marked as deleted. This should actually be filtered very reliably. Are you sure that you have unsubscripted the course.

It's usually for me to unsubscribe from a course when I have passed it.
The problem is that the files' course will be downloaded again when I'll subscribe again to the course (as if the past ones were old).
There's a log file of a test I have made to reproduce the problem.
[MoodleDownloader.log](https://github.com/C0D3D3V/Moodle-Downloader-2/files/6128437/MoodleDownloader.log)

**Comment by C0D3D3V** [comment] 2021-03-12 08:09
A log file with the `-v` option please xD. 

Also please delete the log file first. Then run the downloader four times (with the `-v` option). 
1. with the course activated
2. with the course deactivated
3. with the course deactivated
4. with the course activated

**Comment by marcoscale98** [comment] 2021-03-12 08:13
> A log file with the `-v` option please xD.
> 
> Also please delete the log file first. Then run the downloader four times (with the `-v` option).
> 
> 1. with the course activated
> 2. with the course deactivated
> 3. with the course deactivated
> 4. with the course activated

Yeah, I forgot that ahah.
There's the correct one.
[MoodleDownloader.log](https://github.com/C0D3D3V/Moodle-Downloader-2/files/6128493/MoodleDownloader.log)

**Comment by C0D3D3V** [comment] 2021-03-12 08:34
Mh ok... I see. That is strange. I will try to reproduce it.

**Comment by C0D3D3V** [comment] 2021-04-07 13:21
Was this course set in `download_public_course_ids` or in `download_course_ids`?

**Comment by marcoscale98** [comment] 2021-04-07 13:31
> Was this course set in `download_public_course_ids` or in `download_course_ids`?

download_course_ids

**Comment by C0D3D3V** [comment] 2021-10-01 11:04
I think I understand what you mean now. 

Do you mean when you have selected a course in the Moodle downloader to download, but then online you log out or are logged out of the course. That then all files are marked as deleted by the downloader?

If that's what you mean, I can fix that. This has happened to me as well, and really annoying.

**Comment by marcoscale98** [comment] 2021-10-01 11:09
> I think I understand what you mean now. 
> 
> Do you mean when you have selected a course in the Moodle downloader to download, but then online you log out or are logged out of the course. That then all files are marked as deleted by the downloader?
> 
> If that's what you mean, I can fix that. This has happened to me as well, and is really annoying.

Exactly that

**Closed** 2021-10-01 14:13 UTC
Labels: bug

**Comment by C0D3D3V** [comment] 2021-10-01 14:14
Fixed it, it will be included in the next release
