### ISSUE TITLE
Error in version number determination

### ISSUE THREAD

**Issue by rubisco57** [C0D3D3V/Moodle-Downloader-2#156] opened 2022-09-21 12:42 UTC
I am trying to generate the configuration for site wtih SSO, but the tool throws an error in the `get_simple_moodle_version()` method. From what I can tell, the reason is the nonexistence of the base_url/lib/upgrade.txt. Unfortunately the [wiki entry for manual determination of the version number](https://github.com/C0D3D3V/Moodle-Downloader-2/wiki/Set-user-id-and-Moodle-version-number-manually) also references the file, hence my decision to open an issue. I would appreciate any advice on how to circumvent the problem.  

## Command Line Output
`
Traceback (most recent call last):
  File "C:\tools\anaconda\envs\work\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\tools\anaconda\envs\work\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\tools\anaconda\envs\work\Scripts\moodle-dl.exe\__main__.py", line 7, in <module>
  File "C:\tools\anaconda\envs\work\lib\site-packages\moodle_dl\main.py", line 621, in main
    run_init(storage_path, use_sso, skip_cert_verify)
  File "C:\tools\anaconda\envs\work\lib\site-packages\moodle_dl\main.py", line 74, in run_init
    moodle.interactively_acquire_sso_token()
  File "C:\tools\anaconda\envs\work\lib\site-packages\moodle_dl\moodle_connector\moodle_service.py", line 168, in interactively_acquire_sso_token
    version = RequestHelper(
  File "C:\tools\anaconda\envs\work\lib\site-packages\moodle_dl\moodle_connector\request_helper.py", line 249, in get_simple_moodle_version
    self._check_response_code(response)
  File "C:\tools\anaconda\envs\work\lib\site-packages\moodle_dl\moodle_connector\request_helper.py", line 228, in _check_response_code
    raise RequestRejectedError(
moodle_dl.moodle_connector.request_helper.RequestRejectedError: An Unexpected Error happened on side of the Moodle System! Status-Code: 404
Header: {...}
Response: ...
`
## Reproduction
You can log into the site as a guest [here](https://moodle-app2.let.ethz.ch/).

## Technical details
 - OS: Windows 11 21H2 Build 22000.918
 - Version: 2.2.1.9

**Comment by C0D3D3V** [comment] 2022-09-21 13:34
Sorry I wrote the entry a little bad :D In that case you can just choose any high version number. E.g. 2022041900 which corresponds to version 4.0.
In principle there are more ways to find out the exact version, but that is actually unnecessary, an arbitrarily high is enough. I should take some time and rewrite the code so that you don't need the version number anymore.

But anyway in the configuration state this error should not even happen. I will later check what went wrong there.

**Comment by rubisco57** [comment] 2022-09-21 14:08
Thank you very much for your time. I just tried to add the version number to the config file as suggested, strange enough the error persists.

**Comment by C0D3D3V** [comment] 2022-09-21 17:53
I will fix it tomorrow. The problem is, that I forgot to handle the RequestRejectedError

**Comment by C0D3D3V** [comment] 2022-09-26 11:02
Sorry, I had no time in the last days :( But it is now fixed in v2.2.2.0 
You can update using `pip install -U moodle-dl`

**Closed by C0D3D3V** 2022-09-26 11:02 UTC
Labels: bug

**Comment by rubisco57** [comment] 2022-09-27 07:26
Thank you very much, this works! Meanwhile I had resorted to just commenting out the version checking.
