### ISSUE TITLE
Can not acquire SSO token

### ISSUE THREAD

**Issue by dgcntrk** [C0D3D3V/Moodle-Downloader-2#38] opened 2020-06-15 20:24 UTC
Hey there, I am trying to login to moodle but even when I try manual or automatic sso token it never works. Can you please help?

**Comment by dgcntrk** [comment] 2020-06-15 20:34
Ok after looking at the previous issues I was able to get the token but now I am getting this error
<img width="570" alt="Screen Shot 2020-06-15 at 2 33 01 PM" src="https://user-images.githubusercontent.com/35061839/84703322-4da42b00-af15-11ea-8cc7-c164432880e3.png">

**Comment by C0D3D3V** [comment] 2020-06-15 21:13
Did you set the token manual or automatic?

**Comment by dgcntrk** [comment] 2020-06-15 21:14
tried auto, didn't work then set it manually

**Comment by C0D3D3V** [comment] 2020-06-15 21:14
The error says that the token is invalid. But somehow you managed to get a token so it should working. Does the moodle app on Android or IOS work?

**Comment by dgcntrk** [comment] 2020-06-15 21:14
yes

**Comment by C0D3D3V** [comment] 2020-06-15 21:20
So you can try to set the token fully manually. Its a bit complicated but we discussed it here:  
https://github.com/C0D3D3V/Moodle-Downloader-2/issues/4#issuecomment-581629707

If you can not follow the description or it does not work, we can discuss the problem again.

**Comment by C0D3D3V** [comment] 2020-06-15 21:22
What moodle version do you have?

**Comment by dgcntrk** [comment] 2020-06-15 21:23
should be 3.8 if Im not wrong but is there a way to check it for sure

**Comment by dgcntrk** [comment] 2020-06-15 21:25
even after I edit manually still the same error man :/

**Comment by C0D3D3V** [comment] 2020-06-15 21:26
Ok, thats fine. Does your moodle allow guest registrations, so I can test it?

It is printed in the terminal if you try to aquire a sso token.

You can check it by read the newest version in your moodle changelog: https://your.moodle.de/lib/upgrade.txt

**Comment by dgcntrk** [comment] 2020-06-15 21:28
can I send you the guest access privately?

**Comment by C0D3D3V** [comment] 2020-06-15 21:29
Sure, I will test it tomorrow. You should find my email adress in my profil description.

**Comment by dgcntrk** [comment] 2020-06-15 23:34
Thank you. Waiting :)

**Comment by C0D3D3V** [comment] 2020-06-17 13:03
Try the new release btw. there was a change on the sso url

**Comment by dgcntrk** [comment] 2020-06-17 15:29
tried but still token invalid :/

**Comment by C0D3D3V** [comment] 2020-06-17 18:14
So then to help you more I need more details, what exactly you did. I have send you an email, you can answer at any time.

**Comment by C0D3D3V** [comment] 2020-06-17 23:39
I have a new idea. If the mobile app works for you, then you can extract the token from the app. I will wirte a tutorial tomorrow.

**Comment by C0D3D3V** [comment] 2020-06-18 09:33
Please try this:  https://github.com/C0D3D3V/Moodle-Downloader-2/wiki/Copy-a-token-from-the-Moodle-app

I hope this finally helps

**Comment by dgcntrk** [comment] 2020-06-18 16:20
Thanks a lot It's been a busy week couldn't really give you much information but definitely will look into it asap.

**Comment by C0D3D3V** [comment] 2020-06-21 14:25
Just let me know when you've tested it.

**Comment by C0D3D3V** [comment] 2020-07-01 13:15
It should take you only 5 minutes :D

**Comment by dgcntrk** [comment] 2020-07-01 19:58
Sorry about that. It's still not working. If you want I'm up for a virtual meeting :)

**Comment by C0D3D3V** [comment] 2020-07-04 15:18
I have sent you my skype name (same as my email address). You may contact me as soon as you have time.

**Comment by artaeun** [comment] 2020-07-05 11:27
the tutorial does not work with sso login unfortunately

**Comment by C0D3D3V** [comment] 2020-07-05 11:30
Can you specify what is not working?

**Comment by C0D3D3V** [comment] 2020-07-05 11:31
It works for me.

**Comment by C0D3D3V** [comment] 2020-07-05 11:33
The issue is not that he does not get a token but that this token does not work.  If you don't get a token then please open a new issue with the details of what kind of error you get and what moodle you are using...

**Comment by C0D3D3V** [comment] 2020-07-05 11:33
The issue is not that he does not get a token but that this token does not work.  If you don't get a token then please open a new issue with the details of what kind of error you get and what moodle you are using...

**Comment by artaeun** [comment] 2020-07-05 11:43
sorry for the lack of details. 

- Doing it automatically hangs on the instructions:
![image](https://user-images.githubusercontent.com/6439106/86531858-25c93700-bec5-11ea-996a-dcaf6dc45e13.png)
I tried it from both latest Firefox and from Google Chrome.

- Doing it manually by following the instructions took me to the token code, but once I input the address from the developer console i get this:
![image](https://user-images.githubusercontent.com/6439106/86531842-fe726a00-bec4-11ea-823c-b6e264288196.png)
Translated from italian : the token is not valid/was not found.

- Doing it from the tutorial, after inserting the link to the moodle I'm using, it does not prompt SSO login, thus fails to loginwith my user credentials.

**Comment by C0D3D3V** [comment] 2020-07-05 12:20
Mh, yes seems to be the same or a similar problem. You can also contact me via skype. My username is my email address, you should find it on my profil.

**Comment by C0D3D3V** [comment] 2020-07-09 15:58
In principle I have to rely on your support around the topic SSO, because none of the universities I have access to offer SSO in combination with the Moodle app.

I can only test very few specialties with my own test Moodle.  Without you, I can't get these problems solved.

**Comment by C0D3D3V** [comment] 2020-07-13 16:17
I close the issue now, if anyone else has a problem getting or using their SSO token, please open a new issue.

**Closed by C0D3D3V** 2020-07-13 16:17 UTC
